groups:
- name: example
  rules:
  - alert: TrainingDataStopped
    expr: (delta(waggle_training_data_total[1h]) and waggle_training_data_total > 0) <= 0
    for: 12h
    labels:
      severity: page
    annotations:
      summary: No longer getting new training data.
