# my global config
global:
  scrape_interval:     1m
  evaluation_interval: 1m

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'waggle_training_data'
    metrics_path: '/public/waggle/private/training_data/metrics.php'
    scheme: 'https'
    static_configs:
    - targets: ['web.lcrc.anl.gov:443']
